# file:   .travis.yml
# author: Jess Robertson
# date:   October 2019

language: python

python:
  - "3.6"
  - "3.7"

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
    - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  # Push in dummy credentials to keep boto happy
  - mkdir -p ~/.aws
  - echo $'[default]\naws_access_key_id = f0o\naws_secret_access_key = bAr' > ~/.aws/credentials

install:
  # Install everything with our pipenv
  - pip install pipenv codacy-coverage
  - pipenv install --ignore-pipfile --dev

# command to run tests
script:
  - pipenv run pytest

after_success:
  - python-codacy-coverage -r tests/reports/coverage.xml
